#!/usr/bin/env bash
#
# Script to setup simlinks of config files in this repo into $HOME/.config

CONFIG_DIR=$HOME/.config
DOTFILES_DIR=$(pwd)

err() {
    >&2 echo $1
}

# Ensures script is running in the dotfiles dir
check_in_pwd() {
    if [ ! -f "$DOTFILES_DIR/setup-symlinks" ]; then
        err "script needs to be run from the root of the dotfiles repo"
        exit 1
    fi
}

# Symlinks the passed file/dir to the config dir
setup_symlink() {
    local dir=$1

    if [ ! -d "$DOTFILES_DIR/$dir" ]; then
        err "couldn't find $dir in dotfiles dir, skipping symlink"
        return
    fi

    if [ -d "$CONFIG_DIR/$dir" ]; then
        err "$dir is already in $CONFIG_DIR, skipping symlink"
        return
    fi

    ln -sf "$DOTFILES_DIR/$dir" "$CONFIG_DIR"
    echo "symlinked $dir"
}

main() {
    check_in_pwd

    configs=( "sway" )

    for config in ${configs[@]}; do
        setup_symlink $config
    done
}

main
